ci, build: update CI, libraries, python dependencies, and format
canonical/kubeflow-profiles-operator pull request #131
Opened 2023-07-21 15:52 UTC by DnPlas

This commit updates the CI with standard CI configuration (juju, actions, deps) that is shared across multiple repositories. All python dependencies are also updated to their latest working versions. This PR also includes library updates. Finally, some formatting was applied on non-compliant files (copyright, style).

2023-07-25 11:07 UTC, NohaIhab submitted a review, later dismissed
LGTM

2023-07-25 11:09 UTC, beliaev-maksim requested changes
pls fix CI :)

2023-07-26 07:39 UTC, beliaev-maksim approved these changes

2023-07-26 07:46 UTC, phoevos commented
Shouldn't we also unpin the Juju agent?
```diff
diff --git a/.github/workflows/integrate.yaml b/.github/workflows/integrate.yaml
index d9fd218..f046c22 100644
--- a/.github/workflows/integrate.yaml
+++ b/.github/workflows/integrate.yaml
@@ -54,8 +54,7 @@ jobs:
         with:
           provider: microk8s
           channel: 1.24/stable
-          # Pinned until this bug is resolved: https://bugs.launchpad.net/juju/+bug/1992833
-          bootstrap-options: "--agent-version=2.9.34"
+          juju-channel: 2.9/stable
           charmcraft-channel: latest/candidate
```

2023-07-26 09:27 UTC, phoevos approved these changes

2023-07-26 09:29 UTC, merged